## 应用名称
#  spring.application.name=course-system
#  # 应用服务 WEB 访问端口
#  server.port=8080
#  # 数据库驱动：
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#  # 数据源名称
#  spring.datasource.name=defaultDataSource
#  # 数据库连接地址
#  spring.datasource.url=jdbc:mysql://localhost:3306/javaee?serverTimezone=UTC
#  # 数据库用户名&密码：
#  spring.datasource.username=root
#  spring.datasource.password=778102
#  spring.thymeleaf.prefix=classpath:/templates/


server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/news_release_system?serverTimezone=UTC
    username: root
    password: 778102
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mapper/*.xml

#配置mapper xml文件的路径
mybatis-plus:
  mapper-location: classpath:mapper/*.xml
  #mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #开启驼峰命名转换



